<a href="https://colab.research.google.com/github/DanRHowarth/Artificial-Intelligence-Cloud-and-Edge-Implementations/blob/master/Oxford_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Tutorial

### This tutorial covers the following:
 1. Overview of Numpy 
 2. Introduction to Numpy Arrays
   *  Creating arrays 
   *  Locating elements of an array 
   *  Altering properties of an array, including it's `shape` and `datatype`
 3. Performing operations on Arrays
  * Arithmetic operations
  * Boolean Operations 
  * Universal functions
 
#### Exercises
 * Each section will have an exercise to help reinforce your learning. We suggest you:
   * Write out each line of code by hand (rather than copy and paste it from the relevant example) - this will improve your understanding of code syntax
   * Write out, above each line of code, an explanation as to what the code, using a comment `#` - this will improve your understanding of how the code works

### 1. Overview of Numpy


* [Python for Data Analysis](https://www.amazon.co.uk/Python-Data-Analysis-Wrangling-IPython-ebook/dp/B075X4LT6K/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1540755909&sr=1-1&keywords=python+for+data+analysis ) sets out the following benefits of the Numpy library: 

  * the `ndarray`, an efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities.

  * Mathematical functions for fast operations on entire arrays of data without having to write loops.

  * Tools for reading/writing array data to disk and working with memory-mapped files.

  * Linear algebra, random number generation, and Fourier transform capabilities.


* It is designed for efficiency on large arrays of data because it internally stores data in a contiguous block of memory, independent of other built-in Python objects. Numpy operations perform complex computations on entire arrays without the need for Python for loops.

* See *Python for Data Analysis*, or *[Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/)* (free) for more background on the library and its benefits.


In [2]:
## this simple example will demonstrate the difference in efficiency between numpy and python 

# it is convention to import numpy this way
import numpy as np

# we create our first numpy array - we will come back to this type of operation later 
my_arr = np.arange(1000000)

# create a python list with the same values, but this is obviously not stored as a numpy array
my_list = list(range(1000000))

In [3]:
## let's time how long an operation takes in numpy
%time my_arr2 = my_arr * 2

Wall time: 1.97 ms


In [4]:
# and compare it to the same operation in python
%time my_list2 = [x * 2 for x in my_list]

Wall time: 80.8 ms


### 2. Introduction to Numpy Arrays

* The *N-dimensional array object*, or `ndarray`, is a fast, flexible container for large datasets in Python. Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalent operations between scalar elements.
* In this section, we will cover:
  * How to create arrays
  * How to access different parts of the array 
  * The properties of arrays, and how to modify them.

#### 2.1 Creating arrays
* There are a number of different ways to create an array. We cover some of the main ways here, including:
  * passing in values to the parameters of `np.array`
  * `zeroes`: an array of zero values 
  * `ones`: an array of all ones 
  * `full`: an array of a specified constant value 
  * `random`: an array of random values
  * `eye`: an array with ones on the diagonal and zeroes otherwise
  * converting from a python list
  * `arange`: an array with values within the range specified 
  * `linspace`: an array of equally spaced values within the upper and lower bounds specified
  * `from pandas`
 


In [5]:
# Create an array by passing in values  
a = np.array([0, 1, 2]) 
a

array([0, 1, 2])

In [6]:
# Create a 2D array
b = np.array([[0,1,2],[3,4,5]])  
b

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
# Create an array of all zeros - with three rows of three columns each 
c = np.zeros((3,3)) 
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# Create a 2x2 array of all ones
d = np.ones((2,2)) 
d

array([[1., 1.],
       [1., 1.]])

In [9]:
# Create a 3x3 constant array
e = np.full((3,3), 7) 
e

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [10]:
# Create a 3x3 array filled with random values
f = np.random.random((3,3)) 
f

array([[0.76953623, 0.21868776, 0.39348738],
       [0.18937118, 0.06019846, 0.07333051],
       [0.16992158, 0.65643831, 0.32986506]])

In [11]:
# Create a 3x3 matrix with ones on the diagonal 
# np.identity also returns the same result 
g = np.eye(3)    
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# convert list to array
h = list((2, 3, 1, 0))
h = np.array(h) 
h

array([2, 3, 1, 0])

In [13]:
# arange() will create arrays with regularly incrementing values
i = np.arange(20)
i

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
# linspace() will create arrays with a specified number of items which are 
# spaced equally between the specified beginning and end values
j = np.linspace(2., 4., 5)
j

array([2. , 2.5, 3. , 3.5, 4. ])

#### EXERCISE 2.1: Creating an array
* Create an array using the `np.arange()` function. 
* Use the [documentation](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html) to add start, stop and step parameters 

In [15]:
## EXERCISE CODE HERE

harry = np.arange(20,40,2)
harry

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

#### 2.2 Accessing arrays

* The elements of numpy arrays can be accessed using their index. Numpy (and Pandas) refers to elements *along* the rows as being on `axis 1`, and elements *down* the rows as being on `axis 0`. This is set out below:

![alt text](https://www.safaribooksonline.com/library/view/python-for-data/9781491957653/assets/pyda_0401.png)

* Indexing a 1D array is relatively straightforward as the index values are all on the same axis.
* Indexing a 2D array (or higher dimensions) is slightly trickier, as we need to access `axis 0` first, and then `axis 1`.
* The examples below should make this a little clearer. 


In [16]:
# lets go back to on the first array we created
print("1D array:\n", a)

# we can access the shape of the array like this
print("\nDimensions of array: ", a.shape)

# and call the individual elements of the array using the element's index
print("\nFirst element of array: ", a[0])
print("\nSecond element of array: ", a[1])
print("\nThird element of array: ", a[2])

1D array:
 [0 1 2]

Dimensions of array:  (3,)

First element of array:  0

Second element of array:  1

Third element of array:  2


In [17]:
# lets compare this to a 2D array
print("2D array:\n", b)

# and contrast the shape of this array with the shape of a
print("\nDimensions of 2D array: ", b.shape)

# pause and make sure you understand how the values are being accessed
print("\nArray element [0,0]:", b[0, 0])
print("\nArray elements [1,2] [0,1] [1,0]: ", b[1, 2], b[0, 1], b[1, 0])

2D array:
 [[0 1 2]
 [3 4 5]]

Dimensions of 2D array:  (2, 3)

Array element [0,0]: 0

Array elements [1,2] [0,1] [1,0]:  5 1 3


In [18]:
# We can also slice arrays, using the following approach:

# a[start:end] # items start through end-1
# a[start:]    # items start through the rest of the array
# a[:end]      # items from the beginning through end-1
# a[:]         # a copy of the whole array


# The key point to remember is that the :end value represents the first value that is not in the selected slice. So, the difference 
# beween end and start is the number of elements selected (if step is 1, the default).
# The other feature is that start or end may be a negative number, which means it counts from the end of the array 
# instead of the beginning. So:

# a[-1]    # last item in the array
# a[-2:]   # last two items in the array
# a[:-2]   # everything except the last two items

# create a new array
k = np.array([1,2,3,4])

# access the first two elements
k[0:2]

array([1, 2])

In [19]:
# higher dimension slicing 
j = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# access one row of the array
j[2]

array([ 9, 10, 11, 12])

In [20]:
# access values within one row - note that we can also express this as j[2][:2]
j[2,:2]

array([ 9, 10])

In [21]:
# access all the rows (axis 0) and two of the columns (axis 1)
j[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

#### EXERCISE 2.2: Accessing Arrays 
* Create a 2D array using a different using one of the methods from section 2.1
* Create a new variable containing a slice of the original array
* Replace one of the values of the sliced array using the following template:
  * `array_slice[index_value] = new_value`
* Call the original 2D array and notice if the new_value has been updated  

In [22]:
## EXERCISE CODE HERE

harry_2d = np.array([np.arange(0,10,2),np.arange(10,20,2)])
print('\n2D array: ',harry_2d)
print('\nShape 2D array: ', harry_2d.shape)

var = harry_2d[1,:3]
print('\nSliced array: ', var)

var[1] = 0
print('\nSliced array after change: ',var)
print('\n2D array after change: ',harry_2d)


2D array:  [[ 0  2  4  6  8]
 [10 12 14 16 18]]

Shape 2D array:  (2, 5)

Sliced array:  [10 12 14]

Sliced array after change:  [10  0 14]

2D array after change:  [[ 0  2  4  6  8]
 [10  0 14 16 18]]


#### 2.3 Other properties of arrays
* An ndarray is a generic multidimensional container for homogeneous data. Every array has a shape (which we discoverd above), a tuple indicating the size of each dimension, and a dtype, an object describing the data type of the array
* We can access information on these properties, and alter them, as we will run through below. Operations to reshape the data are common in Deep Learning, and some of the methods used are covered here. 


In [23]:
# One important thing to note that when we can change an element of the array *inplace*
print ("a before changing an element value in place:\n", a)

# change the value at the first elements 
a[0] = 5                 

# and show the result 
print ("\na after changing an element value in place:\n", a)

a before changing an element value in place:
 [0 1 2]

a after changing an element value in place:
 [5 1 2]


In [24]:
# we can access the data type of an array using '.dtype'
print("Data type of a: ", a.dtype)

Data type of a:  int32


In [25]:
# note that numpy automatically assigned us the data type - but we can specify it
a_float = np.array(a, dtype=np.float64)

# print the datatype
print(a_float.dtype)

# and we can see that the array has a decimal point after the number 
a_float

float64


array([5., 1., 2.])

In [26]:
# we can explicitly convert or cast an array from one dtype to another using ndarray’s astype method
a_int32 = a_float.astype(np.int32)

# print the dtype
print(a_int32.dtype)

# and we can see that the numbers have been converted back to integers 
a_int32

int32


array([5, 1, 2])

In [27]:
# Converting from strings to numbers can also be useful
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

# here we use 'float', we could use np.float
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [28]:
# earlier we looked at the .shape attribute. Lets now look at how to reshape numpy arrays 
print(j.shape)

# reshape - noting that the new shape must 'fit' the same number of values 
k = j.reshape(6,2)
k

(3, 4)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [29]:
# passing -1 as the second parameter means numpy will infer the size of the second value
# this is useful if you have large array 

l = np.arange(1500).reshape(2,-1)
l.shape

(2, 750)

In [30]:
# we can join two different arrays either vertically (axis 0) or horizontally (axis 1)
m = np.array([np.arange(0,3),np.arange(3,6), np.arange(6,9)])
n = np.random.random((3,3))

In [31]:
# join - 'stack' vertically - note it takes a tuple as an argument 
o = np.vstack((m,n))
o

array([[0.        , 1.        , 2.        ],
       [3.        , 4.        , 5.        ],
       [6.        , 7.        , 8.        ],
       [0.68323485, 0.58095561, 0.88395354],
       [0.90911967, 0.66759073, 0.34140873],
       [0.27060701, 0.24179887, 0.33016834]])

In [32]:
# stack horizontally
p = np.hstack((m,n))
p

array([[0.        , 1.        , 2.        , 0.68323485, 0.58095561,
        0.88395354],
       [3.        , 4.        , 5.        , 0.90911967, 0.66759073,
        0.34140873],
       [6.        , 7.        , 8.        , 0.27060701, 0.24179887,
        0.33016834]])

In [33]:
# we can then use .ravel() or .flatten() to return 1D arrays
q = o.ravel()
q

array([0.        , 1.        , 2.        , 3.        , 4.        ,
       5.        , 6.        , 7.        , 8.        , 0.68323485,
       0.58095561, 0.88395354, 0.90911967, 0.66759073, 0.34140873,
       0.27060701, 0.24179887, 0.33016834])

In [34]:
# flatten returns a copy of the array, ravel does not - otherwise they perform the same
r = p.flatten()
r

array([0.        , 1.        , 2.        , 0.68323485, 0.58095561,
       0.88395354, 3.        , 4.        , 5.        , 0.90911967,
       0.66759073, 0.34140873, 6.        , 7.        , 8.        ,
       0.27060701, 0.24179887, 0.33016834])

#### EXERCISE 2.3: Properties of Arrays
* Create two 2D arrays
* Reshape one or both of them 
* Stack them together
* Convert this array to a 1D array 

In [35]:
## EXERCISE CODE HERE 

harry_1 = np.array([np.arange(0,10,2),np.arange(10,20,2)])
harry_2 = np.array([np.arange(30,40,2),np.arange(40,50,2)])
print('\n2D array 1: ',harry_1)
print('\n2D array 2: ',harry_2)
print('\nShape 2D array 1: ', harry_1.shape)
print('\nShape 2D array 2: ', harry_2.shape)

harry_1_rs = harry_1.reshape(5,2)
print('\n2D array 1 reshaped: ',harry_1_rs)
print('\nShape 2D array 1 reshaped: ', harry_1_rs.shape)

harry_2_rs = harry_2.reshape(5,2)
print('\n2D array 2 reshaped: ',harry_2_rs)
print('\nShape 2D array 2 reshaped: ', harry_2_rs.shape)

harry_rs_stack = np.hstack((harry_1_rs,harry_2_rs))
print('\nStacked array: ',harry_rs_stack)

harry_rs_stack_1d = harry_rs_stack.ravel()
print('\nReshaped 1D stacked array: ',harry_rs_stack_1d)


2D array 1:  [[ 0  2  4  6  8]
 [10 12 14 16 18]]

2D array 2:  [[30 32 34 36 38]
 [40 42 44 46 48]]

Shape 2D array 1:  (2, 5)

Shape 2D array 2:  (2, 5)

2D array 1 reshaped:  [[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]

Shape 2D array 1 reshaped:  (5, 2)

2D array 2 reshaped:  [[30 32]
 [34 36]
 [38 40]
 [42 44]
 [46 48]]

Shape 2D array 2 reshaped:  (5, 2)

Stacked array:  [[ 0  2 30 32]
 [ 4  6 34 36]
 [ 8 10 38 40]
 [12 14 42 44]
 [16 18 46 48]]

Reshaped 1D stacked array:  [ 0  2 30 32  4  6 34 36  8 10 38 40 12 14 42 44 16 18 46 48]


### 3. Performing Operations on Arrays

* We can perform a range of operations on arrays, including: 
  * Arithmetic operations between arrays
  * Boolean operations 
  * Universal functions
  * Mathematical and Statistical operations 
* We will cover examples of these below; these are not the only operations that can be performed but will provide you with a good toolkit for a range of operations.

In [36]:
# Any arithmetic operations between equal-size arrays applies the operation element-wise:
r + q

array([ 0.        ,  2.        ,  4.        ,  3.68323485,  4.58095561,
        5.88395354,  9.        , 11.        , 13.        ,  1.59235453,
        1.24854634,  1.22536227,  6.90911967,  7.66759073,  8.34140873,
        0.54121402,  0.48359774,  0.66033668])

In [37]:
# we can also use universal functions (ufuncs), a function that performs element-wise operations on data in ndarrays
np.add(m,n)

array([[0.68323485, 1.58095561, 2.88395354],
       [3.90911967, 4.66759073, 5.34140873],
       [6.27060701, 7.24179887, 8.33016834]])

In [38]:
# the same applies to other arithmetic functions
m * n 

array([[0.        , 0.58095561, 1.76790708],
       [2.72735902, 2.67036291, 1.70704364],
       [1.62364207, 1.69259208, 2.64134672]])

In [39]:
# with the ufunc equivalent 
np.multiply(r,q)

array([ 0.        ,  1.        ,  4.        ,  2.04970456,  2.32382245,
        4.41976771, 18.        , 28.        , 40.        ,  0.62114225,
        0.38784058,  0.30178945,  5.45471804,  4.67313509,  2.73126982,
        0.07322815,  0.05846669,  0.10901113])

In [40]:
# the same principles apply to subtraction and division 
# Arithmetic operations with scalars apply the scalar argument to each element in the array
1 / a

array([0.2, 1. , 0.5])

In [41]:
# another example, raising a to the power 0.5
a ** 0.5

array([2.23606798, 1.        , 1.41421356])

In [42]:
# here are a couple more examples 
np.exp(a)

array([148.4131591 ,   2.71828183,   7.3890561 ])

In [43]:
# Elementwise square root
np.sqrt(r)

array([0.        , 1.        , 1.41421356, 0.82658022, 0.76220444,
       0.94018804, 1.73205081, 2.        , 2.23606798, 0.95347767,
       0.81706225, 0.58430191, 2.44948974, 2.64575131, 2.82842712,
       0.52019901, 0.49173048, 0.57460277])

In [44]:
# create two arrays
s = np.random.randn(8)
t = np.random.randn(8)

# compares the arrays 
np.maximum(s, t)

array([ 0.09422313,  1.32408735,  1.57197553, -0.25936144, -1.66898989,
        0.31113046,  1.62656525,  1.66339909])

In [45]:
# statistical methods are available, such as mean(), sum() and cumsum() - cumulative sum()
a.mean()

2.6666666666666665

In [46]:
# this format also works for all the statistical methods
np.sum(a)

8

In [47]:
# we can use boolean operations to filter valies
u = np.array([[1,2], [3, 4], [5, 6]])

# first find the elements of a that are bigger than 2
print("Find elements of array bigger than 2")
print((u > 2))

Find elements of array bigger than 2
[[False False]
 [ True  True]
 [ True  True]]


In [48]:
# then use the mask to get the actual value
print("Values of array elements bigger than 2")
print(u[u > 2])

Values of array elements bigger than 2
[3 4 5 6]


#### EXERCISE: Performing Operations on Arrays
* Create two arrays
* Perform an operation between the two arrays
* Apply a scalar operation to one of the arrays
* Use boolean indexing to select a subset of one of the arrays

In [50]:
## EXERCISE CODE GOES HERE 

arr_1 = np.full((3,3), 8) 
arr_2 = np.eye(3)

print('\nArray 1: ',arr_1)
print('\nArray 2: ',arr_2)

multi = arr_1*arr_2
print('\nMultiplication of both arrays: ',arr_1)

arr_1_div = arr_1/2
print('\nArray 1 divided by 2: ',arr_1_div)

print('\nValues of array 2 elements equal to 1: ', arr_2[arr_2 == 1])


Array 1:  [[8 8 8]
 [8 8 8]
 [8 8 8]]

Array 2:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Multiplication of both arrays:  [[8 8 8]
 [8 8 8]
 [8 8 8]]

Array 1 divided by 2:  [[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]

Values of array 2 elements equal to 1:  [1. 1. 1.]


### Review and Further Reading
* We now have a good background in numpy, in particular what the library is and the benefit of vectorized operations over the approach taken by python on its own; how to create and locate values in arrays; how to perform operations on arrays; and how to broadcast between different numpy arrays.
* There is of course much more to learn. We would suggest looking next at:
  * `fancy indexing`
  * `Broadcasting` 
  * Exploring `ufuncs`, mathematical and statistical operations in greater detail
  * Array-Oriented Programming with Arrays
  * Expressing Conditional Logic as Array Operations
  * Linear Algebra



* Here are some follow-up resources:
  * http://cs231n.github.io/python-numpy-tutorial/
  * the books linked to at the start of the tutorial

